import * as vis from "vis";

export const datagram = {
    nodes: [{
        id: 0,
        label: 'alpha-1',
        image: './img/user.png',
        x: -450,
        y: 0
    }, {
        id: 1,
        label: 'bravo-2',
        image: './img/user.png',
        x: -450,
        y: 100
    }, {
        id: 2,
        label: 'charlie-3',
        image: './img/user.png',
        x: -450,
        y: 200
    }, {
        id: 3,
        label: 'delta-4',
        image: './img/api.png',
        x: -150,
        y: -220
    }, {
        id: 4,
        label: 'echo-5',
        image: './img/api.png',
        x: -150,
        y: -50
    }, {
        id: 5,
        label: 'foxtrot-6',
        image: './img/api.png',
        x: -150,
        y: 150
    }, {
        id: 6,
        label: 'golf-7',
        image: './img/cloud.png',
        x: 150,
        y: 20
    }, {
        id: 7,
        label: 'hotel-8',
        image: './img/cloud.png',
        x: 150,
        y: 150
    }, {
        id: 8,
        label: 'india-9',
        image: './img/disk.png',
        x: 450,
        y: 0
    }, {
        id: 9,
        label: 'juliett-10',
        image: './img/disk.png',
        x: 450,
        y: 250
    }],
    edges: [{
        from: 0,
        to: 3
    }, {
        from: 0,
        to: 4
    }, {
        from: 1,
        to: 4
    }, {
        from: 1,
        to: 5
    }, {
        from: 2,
        to: 5
    }, {
        from: 2,
        to: 9
    }, {
        from: 3,
        to: 8
    }, {
        from: 4,
        to: 6
    }, {
        from: 4,
        to: 7
    }, {
        from: 6,
        to: 8
    }, {
        from: 6,
        to: 9
    }]
}
